### PR TITLE
Seals are now corporeal and can't walk through walls

### PR DESCRIPTION
**Pull request by TsebMagi**

### CODE REVIEW

**Comment by peschkaj** [comment]
I can currently walk through walls.

image

Also - seal movement is pretty crazy pants. It works for now, but we should eventually fine tune that.

**Comment by TsebMagi** [comment]
How did you walk through the wall?
I tried really hard to get it to let me through.

**Comment by peschkaj** [comment]
I have no idea, but I initially had to drag crap into the scene. Right now this is what my scene pane looks like:

image

From what I can remember of your screen, I suspect that we've left something out via the `.gitignore` that should be there.

**Comment by TsebMagi** [comment]
image
This should be the screen before hitting play?

**Comment by peschkaj** [comment]
:+1: that's what I'm seeing, too.

But something really weird is going on over here. When I get to the wall, the seal is disappearing behind the wall, but he'll pass through it.

**Comment by TsebMagi** [comment]
That means that somewhere I the update to the blocking layer didn't get updated correctly, which sounds like .gitignore

**Comment by TsebMagi** [comment]
Try that new one

**Comment by peschkaj** [comment]
Bright side - I can dance on top of walls.
Crappy side - Pretty sure that's not what you want.
image

I did a separate check out and that didn't work, too.

**Comment by TsebMagi** [comment]
well that's weird.

**Comment by TsebMagi** [comment]
try that?

**Comment by peschkaj** [comment]
I'm stuck in a box! :+1: merging

**Pull request merged**
